Resources:
  MyInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-090fa75af13c156b4
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref webServerSG
      UserData:
        'Fn::Base64':
          !Sub |
            #!/bin/bash -xe
            yum update -y aws-cfn-bootstrap
            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource MyInstance --configsets setup --region ${AWS::Region}
            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource MyInstance --region ${AWS::Region}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: bcc0f4f2-ed7d-4e41-ae18-22f263a25370
      'AWS::CloudFormation::Init':
        configSets:
          setup:
            - install_server
        install_server:
          packages:
            yum:
              golang: []
          commands:
            001_clone_repo:
              command: |
                sudo -H -u ec2-user bash -c "cd /home/ec2-user/ && git clone https://github.com/brucedlg/awslab1.git"
            002_run:
              command: |
                sudo -H -u ec2-user bash -c "cd /home/ec2-user && go install github.com/brucedlg/awslab1@latest"
            003_run:
              command: |
                sudo -H -u ec2-user bash -c "cd /home/ec2-user/awslab1 && nohup /home/ec2-user/go/bin/awslab1 &"
  webServerSG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: !Ref SecurityGroupDescription
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
        - CidrIp: 0.0.0.0/0
          FromPort: 8080
          IpProtocol: tcp
          ToPort: 8080
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 740bd1fe-b9dd-42ee-9725-480332ed722d
Metadata:
  'AWS::CloudFormation::Designer':
    bcc0f4f2-ed7d-4e41-ae18-22f263a25370:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 90
      z: 1
      embeds: []
      isassociatedwith:
        - 740bd1fe-b9dd-42ee-9725-480332ed722d
    740bd1fe-b9dd-42ee-9725-480332ed722d:
      size:
        width: 60
        height: 60
      position:
        x: 198.0054244886355
        'y': 130.1932426229617
      z: 0
      embeds: []
Parameters:
  SecurityGroupDescription:
    Description: Security Group Description
    Type: String
  KeyName:
    Description: The EC2 Key Pair to allow SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
